import { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";
import AddTask from "../components/AddTask";
import NavBar from "../components/NavBar";
import TaskList from "../components/TaskList";
import { deleteSingleTask, getAllTask } from "../services/service";
import { ITask } from "../type/ITask";

type TaskType = {
  tasks: ITask[];
};

const Home: NextPage<TaskType> = ({ tasks }) => {
  useEffect(() => {
    getServerSideProps;
  }, []);
  return (
    <div className="bg-gray-50 min-h-screen">
      <Head>
        <title>Task App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="py-4 mx-auto px-4">
        <AddTask />
        <TaskList tasks={tasks} />
      </main>
    </div>
  );
};
export const getServerSideProps: GetServerSideProps<TaskType> = async () => {
  const response = await getAllTask();
  const tasks = await response.json();
  return {
    props: { tasks },
  };
};

export default Home;
